"""Initial migration

Revision ID: 04b171e5b5cc
Revises: 
Create Date: 2023-03-22 23:25:19.388110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b171e5b5cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_venue', sa.String(length=255), nullable=False),
    sa.Column('origin_vendor', sa.String(length=255), nullable=False),
    sa.Column('lot_sku_id', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('main_category', sa.String(length=255), nullable=False),
    sa.Column('venue_transaction_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_lot')
    # ### end Alembic commands ###
