"""attempting to change order.total_sale_price to a property

Revision ID: 0f49499356dd
Revises: 7476dfcfecfc
Create Date: 2023-05-30 23:50:36.076519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f49499356dd'
down_revision = '7476dfcfecfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount_paid', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
