"""Add quanity field to LineItem

Revision ID: 411db106e8e6
Revises: 79f876fad9b6
Create Date: 2023-05-27 14:26:11.467547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411db106e8e6'
down_revision = '79f876fad9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
