"""attempting to change net_revenue to a hybrid property

Revision ID: 7476dfcfecfc
Revises: a0ce21d21f54
Create Date: 2023-05-30 23:39:10.469301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7476dfcfecfc'
down_revision = 'a0ce21d21f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('net_revenue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_revenue', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
