"""Added some fields to order model, including net_revenue

Revision ID: a0ce21d21f54
Revises: 411db106e8e6
Create Date: 2023-05-30 14:25:29.506667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ce21d21f54'
down_revision = '411db106e8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_venue', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('shipping_charged', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('net_revenue', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('net_revenue')
        batch_op.drop_column('shipping_charged')
        batch_op.drop_column('order_venue')

    # ### end Alembic commands ###
