"""turned line item shipping into dynamic calculation

Revision ID: b086d5240093
Revises: f0069081470b
Create Date: 2023-05-31 00:36:12.768537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b086d5240093'
down_revision = 'f0069081470b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_shipping_cost', sa.Float(), nullable=False))
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.FLOAT(), nullable=False))
        batch_op.drop_column('_shipping_cost')

    # ### end Alembic commands ###
