"""fresh start for all models

Revision ID: f7ccd817cf51
Revises: 
Create Date: 2023-05-31 23:37:37.178648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ccd817cf51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_venue', sa.String(), nullable=False),
    sa.Column('_shipping_cost', sa.Float(), nullable=False),
    sa.Column('_fees', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('purchase_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_identifer', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_venue', sa.String(length=255), nullable=False),
    sa.Column('venue_transaction_number', sa.String(length=255), nullable=True),
    sa.Column('origin_vendor', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ONLINE_ARBITRAGE', 'RETAIL_ARBITRAGE', 'LIQUIDATION', 'WHOLESALE', 'THRIFT', 'OTHER', name='purchaselottype'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('main_category', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('units_received', sa.Integer(), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('subtotal_cost', sa.Float(), nullable=False),
    sa.Column('purchase_fees', sa.Float(), nullable=False),
    sa.Column('inbound_shipping_cost', sa.Float(), nullable=False),
    sa.Column('other_cost', sa.Float(), nullable=False),
    sa.Column('discounts', sa.Float(), nullable=False),
    sa.Column('purchase_taxes', sa.Float(), nullable=False),
    sa.Column('link_to_purchase_page', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_identifer')
    )
    op.create_table('items',
    sa.Column('purchase_lot_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('units_received', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_lot_id'], ['purchase_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('line_item_id', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('booking_entry', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('total_sale_price', sa.Float(), nullable=False),
    sa.Column('shipping_charged', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total_amount_paid', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_items')
    op.drop_table('transactions')
    op.drop_table('items')
    op.drop_table('purchase_lots')
    op.drop_table('orders')
    # ### end Alembic commands ###
